language: php
php:
    - "5.5"
before_script:
    - sudo apt-get update > /dev/null
#    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl libapache2-mod-fastcgi
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl libapache2-mod-fastcgi


# begin part from http://about.travis-ci.org/docs/user/languages/php/
   # enable php-fpm
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
   # configure apache virtual hosts
    - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
    - sudo service apache2 restart
# end part from http://about.travis-ci.org/docs/user/languages/php/


# from http://shashikantjagtap.net/using-zombie-js-driver-with-behats-minkextension/
    - sudo apt-get install python-software-properties
    - yes | sudo add-apt-repository ppa:chris-lea/node.js
    - sudo apt-get update
    #- sudo apt-get install nodejs nodejs-dev npm
    - sudo apt-get install  nodejs-dev npm

    - composer self-update
    - composer install --no-interaction --prefer-dist
    #- sh -e /etc/init.d/xvfb start
    #- export DISPLAY=:99.0
    #- wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar
    #- java -jar selenium-server-standalone-2.31.0.jar > /dev/null &
    - sleep 5



script:
    - env NODE_PATH="/usr/lib/node_modules" ./bin/behat
